/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as HotspotsRouteImport } from './routes/hotspots'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HotspotsRoute = HotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/events': typeof EventsRoute
  '/hotspots': typeof HotspotsRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/support': typeof SupportRoute
  '/triage': typeof TriageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/events': typeof EventsRoute
  '/hotspots': typeof HotspotsRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/support': typeof SupportRoute
  '/triage': typeof TriageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/events': typeof EventsRoute
  '/hotspots': typeof HotspotsRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/support': typeof SupportRoute
  '/triage': typeof TriageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/events'
    | '/hotspots'
    | '/live-map'
    | '/login'
    | '/predictions'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/support'
    | '/triage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/events'
    | '/hotspots'
    | '/live-map'
    | '/login'
    | '/predictions'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/support'
    | '/triage'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/events'
    | '/hotspots'
    | '/live-map'
    | '/login'
    | '/predictions'
    | '/reports'
    | '/settings'
    | '/simulator'
    | '/support'
    | '/triage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  EventsRoute: typeof EventsRoute
  HotspotsRoute: typeof HotspotsRoute
  LiveMapRoute: typeof LiveMapRoute
  LoginRoute: typeof LoginRoute
  PredictionsRoute: typeof PredictionsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  SupportRoute: typeof SupportRoute
  TriageRoute: typeof TriageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotspots': {
      id: '/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof HotspotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  EventsRoute: EventsRoute,
  HotspotsRoute: HotspotsRoute,
  LiveMapRoute: LiveMapRoute,
  LoginRoute: LoginRoute,
  PredictionsRoute: PredictionsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  SupportRoute: SupportRoute,
  TriageRoute: TriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
